version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: unless-stopped
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
      - API_PREFIX=${API_PREFIX}
      - API_V1_STR=${API_V1_STR}
      - DEBUG=${DEBUG}
      # Database settings
      - POSTGRES_SERVER=${POSTGRES_SERVER}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      # Application settings
      - BACKEND_CORS_ORIGINS=${DEV_CORS_ORIGINS}
      - HOST=${HOST}
      - PORT=${PORT}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE}
      # Worker settings
      - WEB_CONCURRENCY=${WEB_CONCURRENCY}
      - MAX_WORKERS=${MAX_WORKERS}
      # Test-specific environment variables
      - TEST_POSTGRES_SERVER=${TEST_POSTGRES_SERVER}
      - TEST_POSTGRES_USER=${TEST_POSTGRES_USER}
      - TEST_POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD}
      - TEST_POSTGRES_DB=${TEST_POSTGRES_DB}
      - TEST_POSTGRES_PORT=${TEST_POSTGRES_PORT}
      - TEST_DEBUG=${TEST_DEBUG}
      - PYTEST_ADDOPTS=${PYTEST_ADDOPTS}
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
      - ./alembic:/app/alembic
      - ./pytest.ini:/app/pytest.ini
      - coverage-reports:/app/coverage-reports
    depends_on:
      db:
        condition: service_healthy
      test_db:
        condition: service_healthy
    networks:
      - web
      - backend
    labels:
      - "traefik.enable=true"
      # HTTP Router
      - "traefik.http.routers.web-app.rule=Host(`${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.web-app.entrypoints=web"
      - "traefik.http.routers.web-app.middlewares=https-redirect"
      # HTTPS Router
      - "traefik.http.routers.websecure-app.rule=Host(`${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.websecure-app.entrypoints=websecure"
      - "traefik.http.routers.websecure-app.middlewares=cors-headers,secure-headers,security-headers,scheme-enforcer"
      - "traefik.http.routers.websecure-app.tls=true"
      # Service
      - "traefik.http.services.app.loadbalancer.server.port=8000"
      # Middleware - HTTPS Redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https-redirect.redirectscheme.permanent=true"
      # Middleware - CORS Headers
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolalloworiginlist=*"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.cors-headers.headers.accesscontrolmaxage=3600"
      - "traefik.http.middlewares.cors-headers.headers.addvaryheader=true"
      # Middleware - Secure Headers
      - "traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.secure-headers.headers.customrequestheaders.X-Forwarded-Host=localhost"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.Strict-Transport-Security=max-age=31536000; includeSubDomains; preload"
      - "traefik.http.middlewares.secure-headers.headers.customresponseheaders.X-Scheme=https"
      - "traefik.http.middlewares.secure-headers.headers.hostsproxyheaders=X-Forwarded-Host,X-Forwarded-Proto,X-Real-IP"
      # Middleware - Security Headers for Development
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.Content-Security-Policy=default-src 'self' 'unsafe-inline' 'unsafe-eval' https: http: data: blob: ws:; frame-ancestors 'self'; img-src 'self' https: http: data: blob:; font-src 'self' https: http: data:; form-action 'self'; media-src 'self' https: http: data: blob:; connect-src 'self' https: http: ws: wss:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: http:; style-src 'self' 'unsafe-inline' https: http:;"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.security-headers.headers.customresponseheaders.Referrer-Policy=strict-origin-when-cross-origin"
      # Force HTTPS scheme for all requests
      - "traefik.http.middlewares.scheme-enforcer.headers.customrequestheaders.X-Forwarded-Proto=https"

  db:
    image: postgres:16-alpine
    container_name: postgres_main
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-your-secure-password}
      - POSTGRES_DB=${POSTGRES_DB:-user_management}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16-alpine
    container_name: postgres_test
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${TEST_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${TEST_POSTGRES_PASSWORD:-change-in-production}
      - POSTGRES_DB=${TEST_POSTGRES_DB:-test_user_management}
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${TEST_POSTGRES_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/traefik/traefik.dev.yml:/etc/traefik/traefik.yml:ro
      - traefik_certs:/etc/traefik/acme:rw
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DEV_DOMAIN:-localhost}`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls=true"

networks:
  web:
    external: true
  backend:
    external: false

volumes:
  postgres_data:
    driver: local
  traefik_certs:
    driver: local
  coverage-reports:
    driver: local 