api:
  dashboard: true
  insecure: true  # For local development only

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
    watch: true
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

log:
  level: DEBUG  # More verbose logging for debugging

accessLog: {}

metrics:
  prometheus: {} 