api:
  dashboard: true
  insecure: true  # Only for development

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: default
        domains:
          - main: "localhost"
            sans:
              - "*.localhost"
  metrics:
    address: ":8082"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
    watch: true

# Development-only TLS configuration
certificatesResolvers:
  default:
    acme:
      email: "dev@localhost"
      storage: "/etc/traefik/acme/acme.json"
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"  # Staging server for development
      httpChallenge:
        entryPoint: web

log:
  level: DEBUG  # More verbose logging for development
  format: common

accessLog:
  format: common
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
    names:
      ClientAddr: keep
      ClientHost: keep
      ClientPort: keep
      ClientUsername: keep
      DownstreamStatus: keep
      DownstreamStatusLine: keep
      Duration: keep
      RequestAddr: keep
      RequestHost: keep
      RequestMethod: keep
      RequestPath: keep
      RequestPort: keep
      RequestProtocol: keep
      RequestScheme: keep
      RetryAttempts: keep
      RouterName: keep
      StartLocal: keep
      StartUTC: keep
      level: keep

metrics:
  prometheus:
    entryPoint: metrics

pilot:
  dashboard: false 